name: Bug Report
description: Report a bug in electron-events
type: 'bug'
labels: "bug"
body:
- type: input
  attributes:
    label: Electron Version
    description: |
      What version of Electron are you using?
    placeholder: 30.0.0
  validations:
    required: true
- type: input
  attributes:
    label: electron-events Version
    description: |
      What version of electron-events are you using?
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system(s) are you using?
    multiple: true
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
    placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true
- type: dropdown
  attributes:
    label: What arch are you using?
    options:
      - x64
      - ia32
      - arm64 (including Apple Silicon)
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Last Known Working Electron version
    description: What is the last version of Electron this worked in, if applicable?
    placeholder: 30.0.0
- type: input
  attributes:
    label: Last Known Working electron-events version
    description: What is the last version of electron-events this worked in, if applicable?
    placeholder: 1.0.0
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: If your problem needs further explanation, or if the issue you're seeing cannot be reproduced in a gist, please add more information here.
